server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG

zuul:
# A prefix that can added to beginning of all requests.
#  prefix: /api
  ignoredServices: '*'
  routes:
    # Map path to auth service
    auth-service:
      path: /authenticate/**
      serviceId: AUTH-USERS-SERVICE
      stripPrefix: false
      # Exclude authorization from sensitive headers
      sensitiveHeaders: Cookie,Set-Cookie
    users-service:
      path: /users/**
      serviceId: AUTH-USERS-SERVICE
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    blogs-service:
      path: /blog/**
      serviceId: BLOGS-SERVICE
      stripPrefix: false
      sensitiveHeaders:
    comments-service:
      path: /comment/**
      serviceId: BLOGS-SERVICE
      stripPrefix: false
      sensitiveHeaders:
    likes-service:
      path: /likesunlikes/**
      serviceId: BLOGS-SERVICE
      stripPrefix: false
      sensitiveHeaders:
